### PR TITLE
Fixes #18 Simple ACL Implementation

### LINKED ISSUE #18: feature request: white list pattern
or how to enable/config white list pattern

### PR DESCRIPTION
**Pull request by timothyqiu**
This PR mainly adds a "Bypass LAN and mainland China" option to enable the use of ACL feature of `ss-local`.

* To avoid confusion, a "macOS Proxy" header is added for the original three proxy mode menu items.
    * The "macOS Proxy" term is from Charles.app
    * The menu item header style is from "Recent closed tabs" as used in Chrome.app
* A "Bypass LAN and mainland China" option is added.
    * Impletemented by using the `--acl` option from `ss-local`
    * Uses `~/.ShadowsocksX-NG/bypass-lan-china.acl` and will copy the default one if not exist. Thus, this ACL file can be freely modified if the user wants to customize or update it.
    * The default ACL file is copied from the Shadowsocks Android project

As the PAC / Global / Manual mode is actually just configuring the macOS System Proxy and is frequently misunderstood by the user, I decided to leave them as they are, and ACL won't mess with them.

By implementing the "Bypass" feature by `--acl` instead of PAC, programs that don't utilize the system proxy can also benefit from it.

🍺

### CODE REVIEW

**Comment by timothyqiu** [comment]
FYI, to quickly verify it:

    curl --socks5 127.0.0.1:1086 ip.cn

**Comment by timothyqiu** [comment]
Currently if you select both PAC mode and Bypass-LAN-China, the bypass feature won't seem to be working. Because the PAC will make requests off the GFW List connect directly.

If avoiding misunderstandings has higher priority, I wonder if PAC mode should be disabled if Bypass is turned on?

Anyway, the ideal situation will be that GFW List and user rules are also implemented using ACL. So there will only be two macOS proxy modes: On(Global), Off(Manual).

**Comment by timothyqiu** [comment]
Hi, I added a GFW List option for the ACL.

* `gfwlist.acl` is generated by parsing `gfwlist.txt` and `user-rule.txt`
    * The algorithm is mainly ported from the `abp.js` file.
    * Due to a bug in shadowsocks-libev, ACL regular expressions have a 256 character limit. So I have to skip GFW List rules that is longer than 256 characters after converting to ACL format. Currently, only one rule is affected (google's various country specific domains).
* "Update PAC from GFW List" is now "Update GFW List and PAC"
* The `gfwlist.acl` is also updated after editing the user rules.
* A "Proxy All" option is also added. It disables ACL, so you can get the original SSX-NG behavior.

A primary disadvantage is that it takes 1 to 3 seconds to generate `gfwlist.acl`.

So the menu looks like this now:


---

Some suggestions:

ACL rules are just IP / IP ranges / Regular expressions. They are much simpler than the AdBlock Plus filter rules. I think we can change the User Rule to use plain ACL syntax instead of ABP syntax.

Since GFW List and User Rule can be expressed in ACL, you'll have no reason to use the PAC proxy mode (SOCKS5 / HTTP proxy can be used instead). I think a further update could be making the "macOS Proxy" section just an on/off toggle, and completely remove PAC support.

**Comment by timothyqiu** [comment]
Hi, I changed the implementation a bit:

* Use a generated ACL instead of an existing one.
    * You can use menu to control the content of the generated ACL, including:
        * Default action: Bypass / Proxy
        * Enable GFW List rules
        * Enable bypass LAN and China
    * This leads to a simpler & cleaner implementation.
* ACL won't use PAC user rules any more.
    * Custom rules can be set by creating `~/.ShadowsocksX-NG/custom.acl` in ACL syntax.
    * A dedicated editing window will be added in the future.
* All ACL stuff now goes into a separate sub menu.
* Reverted changes around the original three modes
    * Since ACL options are now in a sub menu, the "macOS Proxy" header is not needed any more.
    * Some helper functions are removed as well.

p.s. I think a refined ACL integration might take a while, so I added a Work-In-Progress sign in the title.

**Comment by timothyqiu** [comment]
Hi, custom rules editing and import / export is ready. I think this is a relatively fully-functioning ACL implementation now.

---

For the whole PR:

* All features in a separate "Shadowsocks ACL" submenu.
* After upgrading to this PR, the default behavior is "Proxy All", same as before upgrading.
* Two presets can be enabled:
    * A "LAN and China" whitelist
    * A "GFW List" blacklist
* Custom rules can be edited in a dedicated window. Custom rules also supports import / export operations.
* The "GFW List" black list preset can be updated from internet.




---

Improvements that can be done in future PRs:
* Table views in the custom rules editing window are only manipulating strings currently. Helper / validation mechanism can be added to help editing rules.
* Updating GFW List ACL is currently done by parsing the GFW List in ABP format.
    * The parser is just a naive parser ported from JavaScript. It can be optimized, and some corner cases might be fixed.
    * Maybe we should just download ACL directly from some trusted source.

---

This PR implements the "whitelist" feature requested in #18 #451

Please review the PR if you have time :) ping @qiuyuzhou

**Comment by timothyqiu** [comment]
Any chance of being accepted? @qiuyuzhou

**Comment by qiuyuzhou** [comment]
同一目的，最好只有一种实现途径。
同时存在多种实现途径会增加未来维护的复杂度。
暂时不考虑。

**Pull request closed without merging**
