### PR TITLE
Supports simple-obfs with SIP003

### LINKED ISSUE #406: Integrate support for plugin ``simple-obfs``
One of the leading distributors of a package for using Shadowsocks servers ``Streisand`` has just merged a PR that enables the ``simple-obfs`` plugin by default.
 (https://github.com/shadowsocks/simple-obfs AND https://github.com/jlund/streisand/pull/743) 

It's said this plugin helps defeat local QOS by ISPs, and could be very useful in China. 

On iOS, Shadowrocket supports simple-obfs settings, can you integrate this into Shadowsocks-NG for Mac OS?

### PR DESCRIPTION
**Pull request by timothyqiu**
This PR hopefully resolves #406 and #576 

To use `simple-obfs`, open the Server Preferences window, set the text fields to something like:
* __Plugin__: `obfs-local`
* __Plugin Opts__: `obfs=http;obfs-host=www.bing.com`

---

I took the prebuilt `obfs-local` binary from Homebrew <sup>[bintray](https://bintray.com/homebrew/bottles/simple-obfs#files)</sup>. Version 0.0.2 for El Capitan is used because it's the version with `ss-local` 3.0.5 and `README.md` says _macOS 10.11+_ is supported.

Changes to the `~/Library/Application Support/ShadowsocksX-NG` directory:
* `simple-obfs-0.0.2/obfs-local` will be copied from the main bundle
* `plugins/obfs-local` will be a symlink to `simple-obfs-0.0.2/obfs-local`

Two extra fields are added to `ServerProfile`: `plugin` and `pluginOptions`, they will be serialized to the `UserDefaults` as `Plugin` and `PluginOptions`.

The JSON config will also have `plugin` and `plugin_opts` if `plugin` is not empty. The `plugin` field in JSON config will have a `plugins` prefix (i.e. `plugins/obfs-local` if `plugin` is set to `obfs-local`). This is required since `ss-local` only searches for the plugin in `PATH`.

The SIP002 QR code can be scanned correctly by the latest Android Shadowsocks client.

---

Something that can be fixed / done in the future:
* Some better way of allowing the user to add plugins. (Currently, users have to symlink their executable to the `plugins` directory.)
* Maybe some way of removing the ugly `plugins/` prefix to the `plugin` config?
* Maybe the legacy QR code needs to include plugin information?

### CODE REVIEW

**Comment by Kaijun** [comment]
Good Job!

**Comment by bzdk** [comment]
thank you @timothyqiu

**Comment by ortonomy** [comment]
@timothyqiu -- BAD ASS!

**Comment by g3org3z** [comment]
@timothyqiu Thanks! Is it possible for you to provide the compiled dmg version on your git page?

**Comment by ortonomy** [comment]
Did this ever get merged?

**Comment by maxming2333** [comment]
life time~

**Comment by ortonomy** [comment]
@timothyqiu -- did you consider requesting the repo admin to review? He's not been requested.

**Comment by timothyqiu** [comment]
@ortonomy I thought creating a pull request without saying "WIP" means requesting review... 😅

Anyway, recent commits in the `develop` branch made this PR unmergeable. I just rebased this PR to the [latest](https://github.com/shadowsocks/ShadowsocksX-NG/tree/e6a22971d82920bf5da9ef84b5efae5314066dc5) `develop` branch and resolved the conflicts.

@qiuyuzhou Please review.

**Comment by g3org3z** [comment]
@timothyqiu Thanks for requesting the review. The latest Obfs plugin version was 0.05. Do you think it's necessary to update it to 0.05? I looked through it briefly and it seemed like the differences were a failover option and multiple bug fixes.

**Comment by timothyqiu** [comment]
@g3org3z I think 0.0.2 may be better because the `ss-local` bundled with SSX-NG is still 3.0.5. As noted in the PR description, `simple-obfs` 0.0.2 kind of matches `ss-local` 3.0.5 considering the release dates.

There's also another consideration: `ss-local` introduced several extra library dependencies in releases after version 3.0.5, so did `simple-obfs` 0.0.3+. These new dependencies are almost the same, and are used to implement similar features (IIRC, they are something related to the DNS). So I think it may be better to add these dependencies when upgrading both `ss-local` and `simple-obfs`.

**Comment by maxming2333** [comment]
@timothyqiu 有 dmg 输出么，貌似这里都不维护了，作者都不管

**Comment by g3org3z** [comment]
@timothyqiu Thanks for the input. I have compiled the obfs branch and while running on my mac with OS 10.11.6, I got the following log:

**Comment by g3org3z** [comment]
@maxming2333 Here you go.

**Comment by maxming2333** [comment]
thx

**Pull request merged**
