### PR TITLE
defaults.array(forKey: "ServerProfiles")  would return nil ,but not h…

### PR DESCRIPTION
**Pull request by linuxbelletian**
…andle

### CODE REVIEW

**Comment by linuxbelletian** [comment]
this update will fix this bug of #89

**Comment by qinyuhang** [comment]
Hi I checked my repo I think maybe we should not using defaults here?

> let mgr = ServerProfileManager.instance
>         for p in mgr.profiles {
>             if mgr.activeProfileId == p.uuid {
>                 if !p.remark.isEmpty {
>                     serverMenuText = p.remark
>                 } else {
>                     serverMenuText = p.serverHost
>                 }
>                 if let latency = p.latency{
>                     serverMenuText += "  - \(latency)ms"
>                 }

**Comment by linuxbelletian** [comment]
It would be better in your way.

**Comment by qinyuhang** [comment]
thank you，let's try this way :D

linuxbelletian <notifications@github.com>于2016年10月18日 周二09:45写道：

**Comment by qiuyuzhou** [comment]
Thanks!

**Pull request merged**
